version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  eureka:
    build:
      context: eureka
      dockerfile: Dockerfile-local
    container_name: eureka
    image: eureka
    ports:
      - "8761:8761"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile-local
    container_name: gateway
    image: gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka:
        condition: service_started
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  config-server:
    build:
      context: config-server
      dockerfile: Dockerfile-local
    container_name: config-server
    image: config-server
    ports:
      - "8888:8888"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  postgres-user-service:
    container_name: postgres-user-service
    image: postgres:16.0
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 2
    volumes:
      - ./postgres-user-service-volume:/var/lib/postgresql/data

  user-service:
    build:
      context: user-service
      dockerfile: Dockerfile-local
    container_name: user-service
    image: user-service
    depends_on:
      eureka:
        condition: service_started
      postgres-user-service:
        condition: service_healthy
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  postgres-restaurant-service:
    container_name: postgres-restaurant-service
    image: postgres:16.0
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 2
    volumes:
      - ./postgres-restaurant-service-volume:/var/lib/postgresql/data

  restaurant-service:
    build:
      context: restaurant-service
      dockerfile: Dockerfile-local
    container_name: restaurant-service
    image: restaurant-service
    depends_on:
      eureka:
        condition: service_started
      postgres-restaurant-service:
        condition: service_healthy
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  postgres-grade-service:
    container_name: postgres-grade-service
    image: postgres:16.0
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 2
    volumes:
      - ./postgres-grade-service-volume:/var/lib/postgresql/data

  grade-service:
    build:
      context: grade-service
      dockerfile: Dockerfile-local
    container_name: grade-service
    image: grade-service
    depends_on:
      eureka:
        condition: service_started
      postgres-restaurant-service:
        condition: service_healthy
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  postgres-black-list-service:
    container_name: postgres-black-list-service
    image: postgres:16.0
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 2
    volumes:
      - ./postgres-black-list-service-volume:/var/lib/postgresql/data

  black-list-service:
    build:
      context: black-list-service
      dockerfile: Dockerfile-local
    container_name: black-list-service
    image: black-list-service
    depends_on:
      eureka:
        condition: service_started
      postgres-black-list-service:
        condition: service_healthy
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  postgres-file-service:
    container_name: postgres-file-service
    image: postgres:16.0
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 2
    volumes:
      - ./postgres-file-service-volume:/var/lib/postgresql/data

  file-service:
    build:
      context: file-service
      dockerfile: Dockerfile-local
    container_name: file-service
    image: file-service
    depends_on:
      eureka:
        condition: service_started
      postgres-file-service:
        condition: service_healthy
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minio_admin
      - MINIO_ROOT_PASSWORD=minio_admin
      - MINIO_VOLUMES=/mnt/data
    command: server ~/minio --console-address :9001
    ports:
      - '9001:9001'
      - '9000:9000'
    volumes:
      - type: bind
        source: minio-volume
        target: /mnt/data

  chat-service:
    build:
      context: chat-service
      dockerfile: Dockerfile-local
    container_name: chat-service
    image: chat-service
    depends_on:
      eureka:
        condition: service_started
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"