version: "3.8"

services:
  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube
    depends_on:
      - postgres-sonar
    ports:
      - "10000:9000"
    networks:
      - sonar
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-sonar:5432/db
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: postgres
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
      - ./sonarqube_temp:/opt/sonarqube/temp

  postgres-sonar:
    image: postgres:16.0
    container_name: postgres-sonar
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - sonar
    volumes:
      - ./postgres/data:/var/lib/postgres/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "sonar" ]
      interval: 5s
      timeout: 1s
      retries: 2


networks:
  sonar:
    driver: bridge
