apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-restaurant-service
  labels:
    app: postgres-restaurant-service
spec:
  serviceName: postgres-restaurant-service
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-restaurant-service
    spec:
      containers:
        - name: postgres-restaurant-service
          image: postgres:16.0
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /data
              name: postgres-restaurant-service-pvc
          env:
            - name: POSTGRES_DB
              value: db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
  selector:
    matchLabels:
      app: postgres-restaurant-service
  volumeClaimTemplates:
    - metadata:
        name: postgres-restaurant-service-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
