apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: ip13/config-server
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          ports:
            - containerPort: 8888