apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  labels:
    app: file-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service
          image: ip13/file-service
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          ports:
            - containerPort: 8500