#!/bin/bash
rm -rf ../jwt-token/mega-admin-token
curl -d @login-mega-admin.json -H 'Content-Type: application/json' http://localhost:8080/auth/login \
| jq  -r .token \
> ../jwt-token/mega-admin-token
