spring:
  application:
    name: gateway

info:
  app:
    name: ${spring.application.name}

server:
  port: 8080

spring.config.import: configserver:http://config-server:8888

spring.cloud:
  config:
    failFast: true
    retry:
      initialInterval: 3000
      maxInterval: 5000
      maxAttempts: 20

logging.level:
  org.springframework.retry: trace

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            nodeValue: TRACE
            route:
              RouteDefinitionLocator: INFO
    reactor.netty.http.client: DEBUG