apiVersion: apps/v1
kind: Deployment
metadata:
  name: black-list-service
  labels:
    app: black-list-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: black-list-service
  template:
    metadata:
      labels:
        app: black-list-service
    spec:
      containers:
        - name: black-list-service
          image: ip13/black-list-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          ports:
            - containerPort: 8500