spring.application.name: user-service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-user-service-service:5432/db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: true
    show_sql: true

info.app.name: ${spring.application.name}

server.port: 8500

spring.config.import: configserver:http://config-server-service:8888

spring.cloud:
  config:
    failFast: true
    retry:
      initialInterval: 3000
      maxInterval: 5000
      maxAttempts: 20

logging.level:
  org.springframework:
    nodeValue: TRACE
    retry: TRACE

spring.jackson.serialization.indent_output: true

management.endpoint.gateway.enabled: true
management.endpoints.web.exposure.include:
  - refresh
  - health
  - flyway
  - beans
  - metrics
  - info

spring.cloud.loadbalancer.ribbon.enabled: false

kafka:
  producer:
    registration-event-producer:
      bootstrap-servers: registration-event-kafka-bootstrap:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.spring.json.type.mapping: registration-event:com.ip13.main.event.RegistrationEvent
  consumer:
    restaurant-created-event-consumer:
      bootstrap-servers: restaurant-created-event-kafka-bootstrap:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: restaurant-created
      properties.spring.json.type.mapping: restaurant-created-event:com.ip13.main.event.RestaurantCreatedEvent

springdoc:
  api-docs:
    path: /auth/v3/api-docs
  swagger-ui:
    path: /auth/swagger-ui.html

eureka.client.enabled: false