spring.application.name: reservation-service

info.app.name: ${spring.application.name}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-reservation-service:5432/db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    preferIpAddress: true

server.port: 0

spring.config.import: configserver:http://config-server:8888

spring.cloud:
  config:
    failFast: true
    retry:
      initialInterval: 3000
      maxInterval: 5000
      maxAttempts: 20

logging.level:
  org.springframework.retry: trace