apiVersion: v1
kind: Service
metadata:
  name: zookeeper-restaurant-created-event-service
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper-restaurant-created-event
