spring:
  application:
    name: booking-system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

security:
  secret: s2UowvHf2hU16VQCMvzESEzh+JCg8NN5OL0gqMpglCggh5OKE+lLmIGLSYqTuacu
  lifeTimeSeconds: 300
  mega_admin: mega_admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka