#!/bin/bash
curl -i -H "Content-Type: application/json" -H "Authorization: Bearer $(cat token)" \
'http://localhost:8080/file/download?objectName=visitor-grade.json&filename=visitor-grade-copy.json&bucket=json'