#!/bin/bash
cd ..
CL='\033[0;33m'
NC='\033[0m'
echo -e "${CL}gradle clean:${NC}"
gradle clean
echo
echo -e "${CL}stop docker containers:${NC}"
docker container stop booking-system db eureka gateway config-server authorization-service postgres-auth-service admin-service
echo
echo -e "${CL}remove docker containers:${NC}"
docker container rm booking-system db eureka gateway config-server authorization-service postgres-auth-service admin-service
echo
echo -e "${CL}remove docker images:${NC}"
docker image rm booking-system:latest eureka:latest gateway:latest config-server:latest authorization-service:latest admin-service:latest