#!/bin/bash
cd ..
CL='\033[0;33m'
NC='\033[0m'
echo -e "${CL}gradle clean:${NC}"
gradle clean
echo
echo -e "${CL}stop docker containers:${NC}"
docker container stop eureka gateway config-server postgres-user-service user-service \
postgres-restaurant-service restaurant-service postgres-grade-service grade-service \
postgres-black-list-service black-list-service postgres-file-service file-service minio chat-service
echo
echo -e "${CL}remove docker containers:${NC}"
docker container rm eureka gateway config-server postgres-user-service user-service \
postgres-restaurant-service restaurant-service postgres-grade-service grade-service \
postgres-black-list-service black-list-service postgres-file-service file-service minio chat-service
echo
echo -e "${CL}remove docker images:${NC}"
docker image rm eureka gateway config-server user-service restaurant-service grade-service black-list-service \
file-service chat-service