#!/bin/bash
cd ..
cd config-server
gradle build -x test
cd ..
cd eureka
gradle build -x test
cd ..
cd gateway
gradle build -x test
cd ..
cd grade-service
gradle build -x test
cd ..
cd restaurant-service
gradle build -x test
cd ..
cd user-service
gradle build -x test
cd ..
cd black-list-service
gradle build -x test
cd ..
cd file-service
gradle build -x test
cd ..
cd chat-service
gradle build -x test
cd ..
