#!/bin/bash
cd ..
cd eureka
gradle build -x test
cd ..
cd gateway
gradle build -x test
cd ..
cd config-server
gradle build -x test
cd ..
cd user-service
gradle build -x test
cd ..
cd reservation-service
gradle build -x test
cd ..
cd restaurant-service
gradle build -x test
cd ..

docker compose up