#!/bin/bash
cd ..
cd booking-system
gradle build -x test
cd ..
cd eureka-server
gradle build -x test
cd ..
cd gateway
gradle build -x test
cd ..
cd config-server
gradle build -x test
cd ..

docker compose up