#!/bin/bash
cd ..
sudo rm -rf postgres-user-service-volume postgres-restaurant-service-volume postgres-grade-service-volume \
postgres-black-list-service-volume postgres-file-service-volume minio-volume