spring.application.name: grade-service

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres-grade-service:5432/db
    username: postgres
    password: postgres
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://postgres-grade-service:5432/db

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int[1,100]}

info.app.name: ${spring.application.name}

server.port: 0

spring.config.import: configserver:http://config-server:8888

spring.cloud:
  config:
    failFast: true
    retry:
      initialInterval: 3000
      maxInterval: 5000
      maxAttempts: 20

logging.level:
  org.springframework:
    nodeValue: TRACE
    retry: TRACE

spring.jackson.serialization.indent_output: true
spring.cloud.loadbalancer.ribbon.enabled: false

springdoc:
  api-docs:
    path: /grade/v3/api-docs
  swagger-ui:
    path: /grade/swagger-ui.html