#!/bin/bash
cd ..
if [ -n "$1" ]
then
  if [ "$1" = "-h" ]
  then
    printf "%s\n" "Global options:"
    printf "\t%-20s%-50s\n" "-test" "run gradle test task. Only for testing env"
    printf "\n"
    printf "print './start -h' for help\n"
  else
    gradle build -x test
    while [ -n "$1" ]
    do
    case "$1" in
      -test)
        gradle test
        gradle jacocoTestReport
        ;;
      *) echo "unknown flag: $1"
    esac
    shift
    done
    docker compose up
  fi
else
  echo "no options specified"
  gradle build -x test
  docker compose up
fi