spring.application.name: restaurant-service

info.app.name: ${spring.application.name}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

server.port: 0

spring.config.import: configserver:http://localhost:8888

spring.cloud:
  config:
    failFast: true
    retry:
      initialInterval: 3000
      maxInterval: 5000
      maxAttempts: 20

logging.level:
  org.springframework.retry: trace

spring:cloud:openfeign:client:config:
  user-service:
    connect-timeout: 2000
    read-timeout: 2000

resilience4j:
  retry:
    instances:
      user-service-retry:
        max-attempts: 5
        wait-duration: 3000

  circuitbreaker:
    instances:
      user-service-breaker:
        sliding-window-type: count-based
        sliding-window-size: 5
        failure-rate-threshold: 80
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2

spring.cloud.loadbalancer.ribbon.enabled: false