name: push to dockerhub

on:
  push:
    paths:
      - user-service
    branches: [ "main" ]

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./user-service
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./user-service/Dockerfile
            image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/restaurant-booking-system
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}