name: push to dockerhub

on:
  push:
    paths:
      - user-service/**
    branches: [ "main" ]

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    env:
      working-directory: user-service
    steps:
      - run : pwd
        working-directory: ${{ env.working-directory }}
      - run : ls -la
        working-directory: ${{ env.working-directory }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          registry: docker.io
          image: ${{ secrets.DOCKERHUB_USERNAME }}/restaurant-booking-system
          tags: 0.0.$GITHUB_RUN_NUMBER, latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
