name: run tests

on:
  pull_request:
    branches: [ "main" ]
  push: 
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        cache: 'gradle'
        cache-dependency-path: | # optional
          sub-project/*.gradle*
          sub-project/**/gradle-wrapper.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test
