name: push user-service image to dockerhub

on:
  push:
    paths:
      - user-service/**
    branches: [ "main" ]

env:
  SERVICE_NAME: user-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_MAIN }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_DIR }}
            git pull
            cd user-service
            ls -la
            kubectl apply -f kubernetes-deployment.yml